# Generated by Django 5.0.2 on 2024-07-14 01:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_remove_organizer_club_name_alter_demand_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='categorie',
            field=models.CharField(choices=[('academic', 'Academic Events'), ('competitions', 'Competitions'), ('social', 'Social Events'), ('cultural', 'Cultural Events'), ('sports', 'Sports Events'), ('career', 'Career Development'), ('club_specific', 'Club-Specific Events'), ('community_service', 'Volunteer & Community Service'), ('technology_innovation', 'Technology & Innovation'), ('educational_workshops', 'Educational Workshops')], default='social', max_length=600),
        ),
        migrations.AlterField(
            model_name='demand',
            name='event',
            field=models.ForeignKey(limit_choices_to={'end_at__lt': datetime.datetime(2024, 7, 14, 1, 6, 19, 82271, tzinfo=datetime.timezone.utc), 'registration_end': False}, on_delete=django.db.models.deletion.CASCADE, to='client.event'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(limit_choices_to={'end_at__lt': datetime.datetime(2024, 7, 14, 1, 6, 19, 82271, tzinfo=datetime.timezone.utc), 'registration_end': False}, on_delete=django.db.models.deletion.CASCADE, to='client.event'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='type_of_account',
            field=models.CharField(choices=[('student', 'Student'), ('club', 'Club')], default='student', max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(limit_choices_to={'end_at__lt': datetime.datetime(2024, 7, 14, 1, 6, 19, 82271, tzinfo=datetime.timezone.utc)}, on_delete=django.db.models.deletion.CASCADE, to='client.event'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='related_event',
            field=models.OneToOneField(limit_choices_to={'end_at__lt': datetime.datetime(2024, 7, 14, 1, 6, 19, 82271, tzinfo=datetime.timezone.utc)}, on_delete=django.db.models.deletion.CASCADE, to='client.event'),
        ),
    ]
