# Generated by Django 5.0.2 on 2024-07-20 19:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_remove_event_is_active_organizer_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='club_wilaya',
            field=models.CharField(choices=[('01', 'Adrar'), ('02', 'Chlef'), ('03', 'Laghouat'), ('04', 'Oum El Bouaghi'), ('05', 'Batna'), ('06', 'Béjaia'), ('07', 'Biskra'), ('08', 'Béchar'), ('09', 'Blida'), ('10', 'Bouira'), ('11', 'Tamanrasset'), ('12', 'Tébessa'), ('13', 'Tlemcen'), ('14', 'Tiaret'), ('15', 'Tizi-Ouzou'), ('16', 'Alger'), ('17', 'Djelfa'), ('18', 'Jijel'), ('19', 'Sétif'), ('20', 'Saïda'), ('21', 'Skikda'), ('22', 'Sidi Bel Abbès'), ('23', 'Annaba'), ('24', 'Guelma'), ('25', 'Constantine'), ('26', 'Médéa'), ('27', 'Mostaganem'), ('28', "M'Sila"), ('29', 'Mascara'), ('30', 'Djelfa'), ('31', 'Oran'), ('32', 'El Bayadh'), ('33', 'Illizi'), ('34', 'Bordj Bou Arreridj'), ('35', 'Boumerdes'), ('36', 'El Tarf'), ('37', 'Tindouf'), ('38', 'Tissemsilt'), ('39', 'El Oued'), ('40', 'Khenchla'), ('41', 'Souk Ahras'), ('42', 'Tipaza'), ('43', 'Tipasa'), ('44', 'Ain Defla'), ('45', 'Naâma'), ('46', 'Ain Témouchent'), ('47', 'Ghardaia'), ('48', 'Relizane'), ('49', 'Timimoun'), ('50', 'Bordj Badji Mokhtar'), ('51', 'Ouled Djellal'), ('52', 'Béni Abbès'), ('53', 'In Salah'), ('54', 'In Guezzam'), ('55', 'Touggourt'), ('56', 'Djanet'), ('57', "El M'Ghair"), ('58', 'El Meniaa')], default='tlemcen', max_length=100),
        ),
        migrations.AlterField(
            model_name='demand',
            name='event',
            field=models.ForeignKey(limit_choices_to={'end_at__lt': datetime.datetime(2024, 7, 20, 19, 21, 54, 898537, tzinfo=datetime.timezone.utc), 'registration_end': False}, on_delete=django.db.models.deletion.CASCADE, to='client.event'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(limit_choices_to={'end_at__lt': datetime.datetime(2024, 7, 20, 19, 21, 54, 898537, tzinfo=datetime.timezone.utc), 'registration_end': False}, on_delete=django.db.models.deletion.CASCADE, to='client.event'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(limit_choices_to={'end_at__lt': datetime.datetime(2024, 7, 20, 19, 21, 54, 898537, tzinfo=datetime.timezone.utc)}, on_delete=django.db.models.deletion.CASCADE, to='client.event'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='related_event',
            field=models.OneToOneField(limit_choices_to={'end_at__lt': datetime.datetime(2024, 7, 20, 19, 21, 54, 897539, tzinfo=datetime.timezone.utc)}, on_delete=django.db.models.deletion.CASCADE, to='client.event'),
        ),
    ]
