# Generated by Django 5.0.2 on 2024-07-28 15:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_event_typep_alter_demand_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='event',
            field=models.ForeignKey(limit_choices_to={'end_at__lt': datetime.datetime(2024, 7, 28, 15, 40, 27, 810554, tzinfo=datetime.timezone.utc), 'registration_end': False}, on_delete=django.db.models.deletion.CASCADE, to='client.event'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(limit_choices_to={'end_at__lt': datetime.datetime(2024, 7, 28, 15, 40, 27, 811598, tzinfo=datetime.timezone.utc), 'registration_end': False}, on_delete=django.db.models.deletion.CASCADE, to='client.event'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(limit_choices_to={'end_at__lt': datetime.datetime(2024, 7, 28, 15, 40, 27, 809555, tzinfo=datetime.timezone.utc)}, on_delete=django.db.models.deletion.CASCADE, to='client.event'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='related_event',
            field=models.OneToOneField(limit_choices_to={'end_at__lt': datetime.datetime(2024, 7, 28, 15, 40, 27, 808556, tzinfo=datetime.timezone.utc)}, on_delete=django.db.models.deletion.CASCADE, to='client.event'),
        ),
    ]
