# Generated by Django 5.0.2 on 2024-08-11 02:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_alter_demand_event_alter_eventregistration_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='event',
            field=models.ForeignKey(limit_choices_to={'end_at__lt': datetime.datetime(2024, 8, 11, 2, 2, 24, 145422, tzinfo=datetime.timezone.utc), 'registration_end': False}, on_delete=django.db.models.deletion.CASCADE, to='client.event'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(limit_choices_to={'end_at__lt': datetime.datetime(2024, 8, 11, 2, 2, 24, 146425, tzinfo=datetime.timezone.utc), 'registration_end': False}, on_delete=django.db.models.deletion.CASCADE, to='client.event'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(limit_choices_to={'end_at__lt': datetime.datetime(2024, 8, 11, 2, 2, 24, 144424, tzinfo=datetime.timezone.utc)}, on_delete=django.db.models.deletion.CASCADE, to='client.event'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='related_event',
            field=models.OneToOneField(limit_choices_to={'end_at__lt': datetime.datetime(2024, 8, 11, 2, 2, 24, 143425, tzinfo=datetime.timezone.utc)}, on_delete=django.db.models.deletion.CASCADE, to='client.event'),
        ),
    ]
